# Generated by Django 5.2.7 on 2025-10-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='dealer_id',
            field=models.IntegerField(default=1),
        ),
    ]
