# Generated by Django 5.2.7 on 2025-10-25 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_carmodel_dealer_id'),
    ]

    operations = [
    ]

# Generated by Django 4.1.3 on 2025-10-25 06:33

from django.db import migrations

def initiate(apps, schema_editor):
    # We get the models from the migration 'apps' registry
    CarMake = apps.get_model('djangoapp', 'CarMake')
    CarModel = apps.get_model('djangoapp', 'CarModel')

    # --- Car Make Data ---
    car_make_data = [
        {"name":"NISSAN", "description":"Great cars. Japanese technology"}, # Index 0
        {"name":"Mercedes", "description":"Great cars. German technology"}, # Index 1
        {"name":"Audi", "description":"Great cars. German technology"}, # Index 2
        {"name":"Kia", "description":"Great cars. Korean technology"}, # Index 3
        {"name":"Toyota", "description":"Great cars. Japanese technology"}, # Index 4
        {"name":"Ford", "description":"American muscle and trucks. Built Ford Tough."}, # Index 5
        {"name":"Honda", "description":"Reliable and efficient. Japanese engineering."}, # Index 6
        {"name":"BMW", "description": "Sheer Driving Pleasure. German engineering."} # Index 7
    ]

    car_make_instances = []
    for data in car_make_data:
            car_make_instances.append(CarMake.objects.create(name=data['name'], description=data['description']))


    # --- Car Model Data ---
    car_model_data = [
      # Nissan (Index 0)
      {"name":"Pathfinder", "type":"SUV", "year": 2023, "car_make":car_make_instances[0], "dealer_id": 1},
      {"name":"Qashqai", "type":"SUV", "year": 2023, "car_make":car_make_instances[0], "dealer_id": 1},
      {"name":"XTRAIL", "type":"SUV", "year": 2023, "car_make":car_make_instances[0], "dealer_id": 1},
      {"name":"Sentra", "type":"Sedan", "year": 2023, "car_make":car_make_instances[0], "dealer_id": 2},
      
      # Mercedes (Index 1) - Corrected types
      {"name":"A-Class", "type":"SEDAN", "year": 2023, "car_make":car_make_instances[1], "dealer_id": 1},
      {"name":"C-Class", "type":"SEDAN", "year": 2023, "car_make":car_make_instances[1], "dealer_id": 1},
      {"name":"E-Class", "type":"SEDAN", "year": 2023, "car_make":car_make_instances[1], "dealer_id": 1},
      {"name":"GLE", "type":"SUV", "year": 2023, "car_make":car_make_instances[1], "dealer_id": 2},

      # ... (include all your other car model data here) ...
      
      # BMW (Index 7)
      {"name":"3 Series", "type":"SEDAN", "year": 2023, "car_make":car_make_instances[7], "dealer_id": 13},
      {"name":"X3", "type":"SUV", "year": 2023, "car_make":car_make_instances[7], "dealer_id": 14},
      {"name":"X5", "type":"SUV", "year": 2023, "car_make":car_make_instances[7], "dealer_id": 14},
    ]

    for data in car_model_data:
            CarModel.objects.create(
                name=data['name'], 
                car_make=data['car_make'], 
                type=data['type'], 
                year=data['year'],
                dealer_id=data['dealer_id']
            )

class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'), # This should point to your PREVIOUS migration
    ]

    operations = [
        migrations.RunPython(initiate) # This tells Django to run your script
    ]