# Generated by Django 5.2.7 on 2025-10-25 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_carmodel_dealer_id'),
        ('djangoapp', '0003_populate_car_data'),
    ]

    operations = [
    ]
